import React, { useState } from "react";
import { LocateFixed, MapPin, Navigation } from "lucide-react";
import { BIHAR_CENTRES } from "../../data/centres";
import { calculateHaversineDistance, getUserCoordinates, findNearestCentre } from "../../utils/sih/geo";

export default function NearestCentreCard() {
  const [loading,setLoading]=useState(false); const [nearest,setNearest]=useState(null); const [error,setError]=useState("");
  const locate=async()=>{setLoading(true);setError("");try{const pos=await getUserCoordinates();const centres=BIHAR_CENTRES.map(c=>({...c,latitude:Number(c.latitude ?? c.lat),longitude:Number(c.longitude ?? c.lon)}));const n=findNearestCentre(centres,pos);if(!n)throw new Error("Centre coordinates are unavailable.");setNearest({...n,distance:calculateHaversineDistance(pos.latitude,pos.longitude,n.latitude,n.longitude)});}catch(e){setError(e.message||"Location unavailable");}finally{setLoading(false);}};
  return <section className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Smart Centre Finder</p><h3 className="mt-1 text-lg font-black text-slate-900">Find nearest procurement centre</h3><p className="mt-1 text-xs text-slate-500">GPS ke basis par nearest Bihar centre identify karein.</p></div><div className="grid h-10 w-10 place-items-center rounded-2xl bg-emerald-50 text-emerald-700"><MapPin size={19}/></div></div><button disabled={loading} onClick={locate} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-50"><LocateFixed size={17}/>{loading?"Finding...":"Use my location"}</button>{error&&<p className="mt-3 text-xs font-semibold text-red-600">{error}</p>}{nearest&&<div className="mt-4 rounded-2xl bg-emerald-50 p-3"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-black text-emerald-950">{nearest.name||nearest.district+" Procurement Centre"}</p><p className="text-xs text-emerald-800">{nearest.district} • {nearest.id||nearest.centre_id}</p></div><span className="rounded-full bg-white px-2.5 py-1 text-xs font-black text-emerald-700">{nearest.distance} km</span></div><a className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-emerald-800" href={`https://www.google.com/maps/dir/?api=1&destination=${nearest.latitude},${nearest.longitude}`} target="_blank" rel="noreferrer"><Navigation size={13}/> Directions</a></div>}</section>;
}
