import React, {useEffect, useState} from 'react';
import {AlertTriangle, CheckCircle2, MessageSquare, Send, Star, MapPinned, RefreshCw} from 'lucide-react';
import { useLanguage } from "../i18n/LanguageContext";
import {api,getApiError} from '../api/api';
import {Card,Pill} from '../components/UI';

export default function Support({user}){const { t } = useLanguage();
 const [grievances,setGrievances]=useState([]),[status,setStatus]=useState([]),[rates,setRates]=useState([]);
 const [form,setForm]=useState({category:'QUEUE',subject:'',description:'',priority:'MEDIUM',token:''});
 const [rating,setRating]=useState(5),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const load=async()=>{try{const results=await Promise.allSettled([api.get(`/grievances/${user.farmer_id}`),api.get(`/public/mandi-status?centre_id=${user.centre_id||""}`),api.get('/rates', { params: { district: user?.district || '' } })]);const value=i=>results[i].status==="fulfilled"?results[i].value:null;const g=value(0),s=value(1),r=value(2);if(g)setGrievances(g.data||[]);if(s)setStatus(s.data?.centres||[]);if(r)setRates(Array.isArray(r.data?.items)?r.data.items:[]);if(results.some(x=>x.status==="rejected"))setMsg(t("auditOptionalUnavailable"))}catch(e){setMsg(getApiError(e,t('paymentLoadFailed')))}};
 useEffect(()=>{load()},[user?.farmer_id,user?.centre_id,user?.district]);
 const submit=async()=>{if(!form.subject||!form.description)return setMsg(t('complaintRequired'));setBusy(true);setMsg('');try{await api.post('/grievances',{farmer_id:user.farmer_id,centre_id:user.centre_id,token:form.token||null,...form});setForm({...form,subject:'',description:'',token:''});setMsg(t('complaintRegistered'));load()}catch(e){setMsg(getApiError(e,t('complaintSubmitFailed')))}finally{setBusy(false)}};
 const feedback=async()=>{setBusy(true);try{await api.post('/feedback',{farmer_id:user.farmer_id,centre_id:user.centre_id,token:(user.last_token || user.token || null),waiting_rating:rating,service_rating:rating,staff_rating:rating,overall_rating:rating,comment});setComment('');setMsg(t('feedbackRecorded'))}catch(e){setMsg(getApiError(e,t('feedbackSubmitFailed')))}finally{setBusy(false)}};
 return <main className="mx-auto max-w-6xl px-4 pb-28 pt-6 md:px-7 md:pb-12">
  <div className="mb-5"><Pill className="bg-emerald-100 text-emerald-800"><MessageSquare size={14}/> {t("supportTitle")}</Pill><h1 className="mt-3 text-3xl font-black">{t("help")}, {t("registerGrievance")} & {t("liveMandiStatus")}</h1><p className="mt-1 text-sm text-slate-500">{t("supportIntro")}</p></div>
  {msg&&<div className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{msg}</div>}
  <div className="grid gap-5 lg:grid-cols-2">
   <Card className="p-5"><div className="flex items-center gap-2"><AlertTriangle className="text-amber-600"/><b>{t("registerGrievance")}</b></div><div className="mt-4 grid gap-3 sm:grid-cols-2">
    <select className="rounded-xl border p-3 text-sm" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['SLOT','QUEUE','WEIGHMENT','QUALITY','PAYMENT','MSP_RATE','J_FORM','STAFF','OTHER'].map(x=><option key={x}>{x}</option>)}</select>
    <select className="rounded-xl border p-3 text-sm" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['LOW','MEDIUM','HIGH','URGENT'].map(x=><option key={x}>{x}</option>)}</select>
    <input className="rounded-xl border p-3 text-sm sm:col-span-2" placeholder={t("tokenOptionalPlaceholder")} value={form.token} onChange={e=>setForm({...form,token:e.target.value})}/>
    <input className="rounded-xl border p-3 text-sm sm:col-span-2" placeholder={t("complaintSubjectPlaceholder")} value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/>
    <textarea rows="4" className="rounded-xl border p-3 text-sm sm:col-span-2" placeholder={t("complaintDescriptionPlaceholder")} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/>
   </div><button disabled={busy} onClick={submit} className="mt-3 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-extrabold text-white"><Send size={15} className="mr-1 inline"/>{t("submitComplaint")}</button></Card>
   <Card className="p-5"><div className="flex items-center gap-2"><MapPinned className="text-indigo-600"/><b>{t("liveMandiStatus")}</b><button onClick={load} className="ml-auto rounded-lg p-2 hover:bg-slate-50"><RefreshCw size={15}/></button></div>{status.map(c=><div key={c.centre_id} className="mt-4 rounded-2xl bg-slate-50 p-4"><div className="flex justify-between"><b>{c.name}</b><Pill className={c.congestion==='HIGH'?'bg-red-100 text-red-700':c.congestion==='MEDIUM'?'bg-amber-100 text-amber-700':'bg-emerald-100 text-emerald-700'}>{c.congestion}</Pill></div><div className="mt-2 grid grid-cols-3 text-xs text-slate-500"><span>{t("queueWord")} <b>{c.active_queue}</b></span><span>{t("loadWord")} <b>{c.utilization_percent}%</b></span><span>{t("doneWord")} <b>{c.completed_today}</b></span></div><p className="mt-2 text-xs font-bold text-slate-600">{c.recommended}</p></div>)}<div className="mt-4"><div className="flex items-center justify-between"><b className="text-sm">{t("currentProcurementRates")}</b><span className="text-[10px] font-bold text-emerald-700">{t("adminRateLabel")} • KisanSetu</span></div><div className="mt-2 grid grid-cols-2 gap-2">{rates.map(r=><div key={r.crop+r.quality_grade} className="rounded-xl border p-3 text-xs"><b>{r.crop}</b><span className="float-right font-black">₹{Number(r.rate_per_kg).toFixed(2)}/kg</span><div className="text-slate-400">{t('centralRate')} • {r.arrival_date || t('today')}</div></div>)}</div></div></Card>
  </div>
  <div className="mt-5 grid gap-5 lg:grid-cols-2">
   <Card className="p-5"><div className="rounded-2xl bg-indigo-50 p-4"><b className="text-sm text-indigo-900">⚖️ {t("transparentDispute")}</b><p className="mt-1 text-xs text-slate-600">{t("transparentDisputeDesc")}</p></div><div className="mt-5"><b>{t("yourComplaints")}</b><div className="mt-4 space-y-3">{grievances.length?grievances.map(g=><div key={g.grievance_id} className="rounded-xl border p-4"><div className="flex justify-between gap-2"><b>{g.subject}</b><Pill className={g.status==='RESOLVED'?'bg-emerald-100 text-emerald-700':'bg-amber-100 text-amber-700'}>{g.status}</Pill></div><p className="mt-1 text-xs text-slate-500">{g.category} • {g.priority}</p><p className="mt-2 text-sm text-slate-600">{g.description}</p>{g.resolution&&<p className="mt-2 rounded-lg bg-emerald-50 p-2 text-xs font-semibold text-emerald-800">{t("resolutionWord")}: {g.resolution}</p>}</div>):<p className="text-sm text-slate-400">{t("noComplaints")}</p>}</div></div></Card>
   <Card className="p-5"><div className="flex items-center gap-2"><Star className="text-amber-500"/><b>{t("rateExperience")}</b></div><div className="mt-4 flex gap-2">{[1,2,3,4,5].map(x=><button key={x} onClick={()=>setRating(x)} className={x<=rating?'text-amber-500':'text-slate-300'}><Star fill="currentColor"/></button>)}</div><textarea rows="3" className="mt-3 w-full rounded-xl border p-3 text-sm" placeholder={t("optionalFeedbackPlaceholder")} value={comment} onChange={e=>setComment(e.target.value)}/><button disabled={busy} onClick={feedback} className="mt-3 rounded-xl bg-indigo-700 px-4 py-3 text-sm font-extrabold text-white"><CheckCircle2 size={15} className="mr-1 inline"/>{t("submitFeedback")}</button></Card>
  </div>
 </main>
}
